#!/usr/bin/env bash

alias hugo=$PWD/bin/hugo

page_type=post
ext=md

[ -z "$1" ] && echo "Please provide post name" && return 1

post_name=`echo $1 | cut -d '.' -f 1`

[ ! -z "$2" ] && page_type="$2"
[ ! -z "$3" ] && ext="$3"

dest="${page_type}/$(date +"%Y-%m-%d")-${post_name}.${ext}"

hugo new --source $PWD/site $dest
