baseURL = "https://nickferguon.dev/"
languageCode = "en-us"
theme = "lanyon-hugo"
pygmentsuseclasses = "true"

[params]
	Title = "Nick's Blog"
	Tagline = "You guys doin' DragonOps?"
	Author = "Nick Ferguson"
	Description = "It works on my machine."
	Copyright = "2021 Nick Ferguson"
	DateForm = "Jan 2 2006"


[menu]
[[menu.main]]
	identifier = "categories"
	name = "Categories"
	title = "Categories"
	url = "/categories/"
	weight = -110
[[menu.main]]
	identifier = "about"
	name = "About Me"
	title = "About Me"
	url = "/about/"
	weight = -100


	
