baseURL = "https://nickferguon.dev/"
languageCode = "en-us"
theme = "lanyon-hugo"
pygmentsuseclasses = "true"

[params]
	Title = "Nick's Blog"
	Description = "Get ready for... DragonOps."
	Author = "Nick Ferguson"
	Tagline = "It works on my machine."
	Copyright = "2021 Nick Ferguson"
	DateForm = "Jan 2 2006"


[menu]
[[menu.main]]
	identifier = "categories"
	name = "Categories"
	title = "Categories"
	url = "/categories/"
	weight = -110


	
