# config/_default/config.toml

baseURL = "//nickferguson.dev"
title	= "nickferguson.dev"
theme	= "noteworthy"

LanguageCode	= "en"
enableRobotsTXT = true

paginate		= 4
summaryLength	= 50 

pygmentsuseclasses = true  # requires style sheet



