# config/_default/params.toml

author = "Nick Ferguson"
description = "Dunno... works on my machine..."
copyright = "2021 Nick Ferguson"
dateform = "Jan 2 2006"

math = true
# Blog description at the top of the homepage. Supports markdown.

showReadMore = true

# Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
enableKofi = false
kofi = ""

# Add links to your accounts. Remove the ones you don't want to include.
# Main
email = "blog@nickferguson.dev"
linkedin = "https://linked.com/in/ncferguson"
#twitter = "#"
#youtube = "#"

# Programming
github = "https://github.com/NickCrew"
#stackoverflow = "#"
#gitlab = "#"
#codepen = "#"


