# config/_default/params.toml

author = "Nick Ferguson"
description = "It works on my machine..."
copyright = "2022 Nick Ferguson"
dateform = "Jan 2 2006"

math = true
# Blog description at the top of the homepage. Supports markdown.

showReadMore = true

# Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
enableKofi = false
kofi = ""

# Add links to your accounts. Remove the ones you don't want to include.
# Main
email = "blog@nickferguson.dev"
linkedin = "https://linkedin.com/in/ncferguson"
github = "https://github.com/NickCrew"
instagram = "https://instagram.com/wildbearattak"
twitter = "https://twitter.com/piggahmonster"
behance = "https://www.behance.net/nicholaferguso1"
#youtube = "https://www.youtube.com/channel/UC972wwbPrKXW-YlXCPGPbQw"
# Programming
#stackoverflow = "https://stackoverflow.com/users/6569965/nicholas-ferguson"
#gitlab = "https://gitlab.com/Nickopotamus"
#codepen = "https://codepen.io/nickcrew"


